import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { useRef, useState } from "react";
export const ChatInput = ({ value, error, isCompactLayout, onChange, onSend, onAddFiles, attachedFiles, onRemoveFile, replyMessage, forwardedMessage, editingMessage, onCancelReply, onCancelForward, onCancelEdit, }) => {
    const fileInputRef = useRef(null);
    const [viewerAttachment, setViewerAttachment] = useState(null);
    const handleKeyDown = (event) => {
        if (event.key === "Enter" && !event.shiftKey) {
            event.preventDefault();
            onSend();
        }
    };
    const handleSelectFiles = async (files, mode) => {
        const nextFiles = Array.from(files ?? []);
        if (nextFiles.length) {
            await onAddFiles(nextFiles, mode);
        }
    };
    return (_jsxs("div", { className: "chat-input-shell", children: [(replyMessage || forwardedMessage || editingMessage) && (_jsxs("div", { className: "chat-input-meta", children: [replyMessage && (_jsxs("div", { className: "chat-input-meta-card", children: [_jsxs("span", { children: ["\u041E\u0442\u0432\u0435\u0442: ", replyMessage.message_text] }), _jsx("button", { type: "button", onClick: onCancelReply, children: "\u00D7" })] })), forwardedMessage && (_jsxs("div", { className: "chat-input-meta-card", children: [_jsxs("span", { children: ["\u041F\u0435\u0440\u0435\u0441\u044B\u043B\u043A\u0430: ", forwardedMessage.message_text] }), _jsx("button", { type: "button", onClick: onCancelForward, children: "\u00D7" })] })), editingMessage && (_jsxs("div", { className: "chat-input-meta-card", children: [_jsx("span", { children: "\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0435 \u0441\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u044F" }), _jsx("button", { type: "button", onClick: onCancelEdit, children: "\u00D7" })] }))] })), attachedFiles.length > 0 && (_jsx("div", { className: "chat-input-files", children: attachedFiles.map((file) => (_jsxs("div", { className: `chat-input-file-chip ${file.type.startsWith("image/") || file.type.startsWith("video/") ? "is-media" : ""}`, children: [(file.type.startsWith("image/") || file.type.startsWith("video/")) && file.preview ? (_jsx("button", { type: "button", className: "chat-input-media-preview", onClick: () => setViewerAttachment(file), children: file.type.startsWith("image/") ? (_jsx("img", { src: file.preview, alt: "" })) : (_jsx("video", { src: file.preview, muted: true, playsInline: true, preload: "metadata" })) })) : (_jsx("span", { children: file.name })), _jsx("button", { type: "button", onClick: () => onRemoveFile(file.id), children: "\u00D7" })] }, file.id))) })), error && _jsx("div", { className: "auth-error", children: error }), _jsxs("div", { className: "chat-input chat-input-modern", children: [_jsx("input", { ref: fileInputRef, type: "file", multiple: true, accept: "image/*,video/*", className: "chat-input-file-hidden", onChange: (event) => {
                            void handleSelectFiles(event.target.files, "compressed");
                            event.target.value = "";
                        } }), _jsx("div", { className: "chat-input-attach-shell", children: _jsx("button", { type: "button", className: "chat-input-attach", onClick: () => fileInputRef.current?.click(), "aria-label": "\u041F\u0440\u0438\u043A\u0440\u0435\u043F\u0438\u0442\u044C \u0444\u0430\u0439\u043B\u044B", children: "+" }) }), _jsx("textarea", { value: value, onChange: (event) => onChange(event.target.value), onKeyDown: handleKeyDown, placeholder: "\u0421\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u0435..." }), _jsx("button", { type: "button", className: "chat-input-send", onClick: onSend, children: "\u279C" })] }), viewerAttachment && viewerAttachment.preview && (_jsx("div", { className: "media-viewer-backdrop", onClick: () => setViewerAttachment(null), children: _jsxs("div", { className: "media-viewer", onClick: (event) => event.stopPropagation(), children: [_jsx("button", { type: "button", className: "media-viewer-close", onClick: () => setViewerAttachment(null), children: "\u0417\u0430\u043A\u0440\u044B\u0442\u044C" }), _jsx("div", { className: "media-viewer-body", children: viewerAttachment.type.startsWith("image/") ? (_jsx("img", { className: "media-viewer-image", src: viewerAttachment.preview, alt: viewerAttachment.name })) : (_jsx("video", { className: "media-viewer-video", src: viewerAttachment.preview, controls: true, autoPlay: true })) })] }) }))] }));
};
